### ISSUE TITLE
URL of homepage on https://luarocks.org/modules/olivine-labs/say

### ISSUE THREAD

**Issue by scls19fr** [lunarmodules/say#15]
Hello,

On https://luarocks.org/modules/olivine-labs/say
homepage is set to http://olivinelabs.com/busted/
it should probably be https://github.com/Olivine-Labs/say instead

Kind regards

**Comment by alerque** [comment]
I've update the URL on the LuaRocks site. Note that the module has been copied into a new org user and the new location is the default if you just search for "say" or download it with luarocks. However if you follow a direct link to the old user you will still see the old module version, links and all, that represents the last published state under that user. New versions will only show up under the new user (luamodules).

**Comment by alerque** [comment]
Current module page:

https://luarocks.org/modules/lunarmodules/say
